#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get -y install nginx
echo "Hello World!" >/var/www/html/index.html
echo "Ceci n'est pas une page" >/var/www/html/404.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://github.com/Sgechuki;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
ln -sf  /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
