#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
echo 'ENABLED=1' >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg-orig
echo '
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 47086-web-01 54.160.100.187:80 check
   server 47086-web-02 35.153.17.253:80 check
' >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
