#!/usr/bin/env bash
#  displays to infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERMx
counter=1
while [ "$counter" -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 1
done
