#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds

filename="/tmp/my_process"
counter=1
while [ "$counter" -eq 1 ]
do
	echo "I am alive!">>"$filename"
	sleep 2
done
