#!/usr/bin/env bash
# make up a story based on etc/passwd


IFS=":"
filename="/etc/passwd"
while read  -r -a arrText
do
	echo "The user ${arrText[0]} is part of the ${arrText[3]} gang, lives in ${arrText[5]} and rides ${arrText[6]}. ${arrText[2]}'s place is protected by the passcode ${arrText[1]}, more info about the user here: ${arrText[4]}"
done < "$filename"
unset IFS
